

name: CD Pipeline

on:
  workflow_run:
    workflows: ["CI Pipeline"]
    types:
      - completed

jobs:

  build:

    runs-on: self-hosted

    steps:
    - name: Login Dockerhub
      env:
        DOCKER_USERNAME: ${{secrets.DOCKER_USERNAME}}
        DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
      run: echo $DOCKER_PASSWORD | sudo docker login ghcr.io -u $DOCKER_USERNAME --password-stdin
    - name: Pull Docker image
      env:
          DOCKER_USERNAME: ${{secrets.DOCKER_USERNAME}}
      run: sudo docker pull ghcr.io/tecosys/cerina:chat
    - name: Delete Old docker container
      run: sudo docker rm -f chatai-container || true
    - name: Delete Old docker containers
      run: sudo docker container prune -f
    - name: Delete Old docker images
      run: sudo docker image prune -f
    - name: Run Docker Container
      run: sudo docker run -d --name chatai-container -p 7878:7878 ghcr.io/tecosys/cerina:chat
